# Generated by Django 4.1.7 on 2023-07-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_admin',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='pswd',
            field=models.CharField(default='', max_length=50),
        ),
    ]
