# Generated by Django 4.1.7 on 2023-07-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0003_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(default='', upload_to='products/')),
                ('qty', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=50)),
                ('details', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
