# Generated by Django 4.1.7 on 2023-07-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0004_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('total_price', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingApp.tbl_product')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingApp.tbl_user')),
            ],
        ),
    ]
